language: r
warnings_are_errors: false
sudo: false
cache: packages

branches:
  only:
    - master
    - stable
    - /^release-.*/
    - /^v.*$/

before_install:
  - sudo apt-get -y install openjdk-8-jre

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    repo: angusmoore/excelMapR
    tags: true

after_success:
  - Rscript -e 'covr::coveralls()'
